### ISSUE TITLE
Removed from mycroft-skills repo

### ISSUE THREAD

**Issue by forslund** [samclane/lifx-mycroft#11]
First of all thanks for creating this skill!

This is a notification that the skill was removed from the 20.02 branch of the mycroft-skills repo due to an requirement issue. It can be included again once #10 has been merged.

**Comment by samclane** [comment]
@forslund 

Thank you so much for helping me maintain this skill! I've started a new job and haven't had the time to devote that I used to.

I've merged the PR. Could you give me a link on how to submit skills back to the repo?  It's been a while and I can't quite remember how.

**Comment by forslund** [comment]
I'll restore it on the repo for you.

**Comment by samclane** [comment]
@forslund The clones of the repo seem to have dropped to 0 and stayed there. Did you have any issues re-adding to the Mycroft repo?

**Comment by forslund** [comment]
Sorry I had an initial issue andhadven't gotten back around to it again. Yell at me again if it's not restored tomorrow

**Comment by forslund** [comment]
Back in the skills repo. Closing issue
